language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - os: osx
    - julia: nightly
  
notifications:
  email: true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - cd $HOME; if [[ ! -d cmdstan ]]; then git clone https://github.com/stan-dev/cmdstan.git; fi
  - cd $HOME/cmdstan; git checkout v2.17.1; make stan-update; make build
  - export CMDSTAN_HOME=$HOME/cmdstan
  - cd $TRAVIS_BUILD_DIR
  - julia -e 'using Pkg; Pkg.test("Stan"; coverage=true)'
after_success:

  #
  # Documentation
  #
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Stan")); include(joinpath("docs", "make.jl"))'

  #
  # Coverage
  #
  
  # push coverage results to Coveralls
  
  - julia -e 'cd(Pkg.dir("Stan")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  
  # push coverage results to Codecov
  
  - julia -e 'cd(Pkg.dir("Stan")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
